# Generated by Django 6.1 on 2026-09-08 15:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone_number', models.CharField(blank=True, max_length=15, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='client_profiles/')),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='JobPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_description', models.TextField()),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('category', models.CharField(choices=[('Driving', 'Driving'), ('Moving', 'Moving'), ('Handyman', 'Handyman'), ('Childcare', 'Childcare'), ('Elder Care', 'Elder Care'), ('Event Staffing', 'Event Staffing'), ('Cooking', 'Cooking'), ('Construction', 'Construction'), ('Security', 'Security'), ('Gardening', 'Gardening'), ('Tutoring', 'Tutoring'), ('Beauty', 'Beauty')], max_length=50)),
                ('price', models.DecimalField(decimal_places=2, help_text='Fair/price offered by client', max_digits=10)),
                ('duration', models.CharField(help_text="e.g. '2 hours', '3 days'", max_length=100)),
                ('start_date', models.DateField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('assigned', 'Assigned'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='open', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_posts', to='Client.clientprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
