# Generated by Django 6.1 on 2026-09-21 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0003_alter_jobpost_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobpost',
            name='category',
            field=models.CharField(choices=[('driving', 'Driving'), ('moving', 'Moving'), ('handyman', 'Handyman'), ('caregiving', 'Care Giving'), ('event_staffing', 'Event Staffing'), ('cooking', 'Cooking'), ('construction', 'Construction'), ('security', 'Security'), ('gardening', 'Gardening'), ('tutoring', 'Tutoring'), ('beauty', 'Beauty'), ('cleaning', 'Cleaning')], max_length=50),
        ),
    ]
