# Generated by Django 6.1 on 2026-09-29 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Client', '0004_alter_jobpost_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Category',
        ),
    ]
