# Generated by Django 6.1 on 2026-09-11 06:44

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Client', '0002_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkerBio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cnic', models.CharField(help_text='Format: 12345-1234567-1', max_length=15, unique=True)),
                ('age', models.PositiveIntegerField(help_text='Age must be between 18 and 100', validators=[django.core.validators.MinValueValidator(18), django.core.validators.MaxValueValidator(100)])),
                ('years_of_experience', models.PositiveIntegerField(default=0, help_text='Total years of experience')),
                ('gender', models.CharField(blank=True, choices=[('M', 'Male'), ('F', 'Female'), ('O', 'Other')], max_length=1)),
                ('bio', models.TextField(blank=True, help_text='Short description about yourself')),
                ('is_verified', models.BooleanField(default=False)),
                ('average_rating', models.DecimalField(decimal_places=2, default=0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('client_profile', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='worker_bio', to='Client.clientprofile')),
                ('expertise_categories', models.ManyToManyField(help_text='Categories worker is expert in', related_name='expert_workers', to='Client.category')),
            ],
        ),
        migrations.CreateModel(
            name='WorkerService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('Driving', 'Driving'), ('Moving', 'Moving'), ('Handyman', 'Handyman'), ('Childcare', 'Childcare'), ('Elder Care', 'Elder Care'), ('Event Staffing', 'Event Staffing'), ('Cooking', 'Cooking'), ('Construction', 'Construction'), ('Security', 'Security'), ('Gardening', 'Gardening'), ('Tutoring', 'Tutoring'), ('Beauty', 'Beauty')], max_length=50)),
                ('job_description', models.TextField(help_text='Description of the service offered')),
                ('city', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=100)),
                ('rate', models.DecimalField(decimal_places=2, help_text="Worker's own asking rate/price", max_digits=10)),
                ('is_available', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='worker.workerbio')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
