# Generated by Django 6.1 on 2026-09-21 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerbio',
            name='expertise_categories',
        ),
        migrations.AlterField(
            model_name='workerservice',
            name='category',
            field=models.CharField(choices=[('driving', 'Driving'), ('moving', 'Moving'), ('handyman', 'Handyman'), ('childcare', 'Child Care'), ('eldercare', 'Elder Care'), ('event_staffing', 'Event Staffing'), ('cooking', 'Cooking'), ('construction', 'Construction'), ('security', 'Security'), ('gardening', 'Gardening'), ('tutoring', 'Tutoring'), ('beauty', 'Beauty'), ('cleaning', 'Cleaning')], max_length=50),
        ),
        migrations.AddField(
            model_name='workerbio',
            name='expertise_categories',
            field=models.CharField(blank=True, choices=[('driving', 'Driving'), ('moving', 'Moving'), ('handyman', 'Handyman'), ('childcare', 'Child Care'), ('eldercare', 'Elder Care'), ('event_staffing', 'Event Staffing'), ('cooking', 'Cooking'), ('construction', 'Construction'), ('security', 'Security'), ('gardening', 'Gardening'), ('tutoring', 'Tutoring'), ('beauty', 'Beauty'), ('cleaning', 'Cleaning')], null=True),
        ),
    ]
