# Generated by Django 6.1 on 2026-09-29 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('worker', '0003_alter_workerbio_expertise_categories_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workerbio',
            name='expertise_categories',
            field=models.CharField(blank=True, choices=[('driving', 'Driving'), ('moving', 'Moving'), ('handyman', 'Handyman'), ('caregiving', 'Care Giving'), ('event_staffing', 'Event Staffing'), ('cooking', 'Cooking'), ('construction', 'Construction'), ('security', 'Security'), ('gardening', 'Gardening'), ('tutoring', 'Tutoring'), ('beauty', 'Beauty'), ('cleaning', 'Cleaning')], max_length=50, null=True),
        ),
    ]
